import Head from 'next/head';
import AboutUs from '../components/AboutUs/AboutUs';
import Blog from '../components/Blog/Blog';
import Clients from '../components/Clients/Clients';
import Footer from '../components/Footer/Footer';
import GetInTouch from '../components/GetInTouch/GetInTouch';
import Hero from '../components/Hero/Hero';
import Navbar from '../components/Navbar/Navbar';
import Services from '../components/Services/Services';
import Status from '../components/Status/Status';
import Team from '../components/Team/Team';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="bg-white">
        <Hero />
        <div className="lg:px-14 space-y-20">
          <Services />
          <AboutUs />
          <GetInTouch />
          <Team />
          <Status />
          <Clients />
          <Blog />
          <Footer />
        </div>
      </main>
    </>
  );
}
